### PR TITLE
Update intro.md

### PR DESCRIPTION
**Pull request by James-OutSystems**
rewrote for clarity

### CODE REVIEW

**Review by James-OutSystems — COMMENTED** [review]
added one more paragraph

**Review by James-OutSystems — COMMENTED** [review]
updates per feedback

**Review by James-OutSystems — COMMENTED** [review]
updated per feedback

**Review by James-OutSystems — COMMENTED** [review]
minor edit

**Review by pacferreira — APPROVED** [review]
Reviewed

**Pull request merged**
