### PR TITLE
Corrected grammatical error in entity-property description-text.

### PR DESCRIPTION
**Pull request by Highbury14**
Should use the present-tense form of the verb 'describe'. 
Not the past-tense form.

### CODE REVIEW

**Comment by Highbury14** [comment]
I read, understood and accept the OutSystems CLA.

**Comment by Highbury14** [comment]
I saw this same grammatical error in the pop-up description text in OutSystems Service-Studio U.I, for this Entity-Property 'label attribute'.

Does it get fixed in the Service-Studio U.I also, when it is updated here in the documentation ?

Or is that in a different repository ?

**Comment by somehost** [comment]
The beta version of ServiceStudio that I am currently on does not appear to have the issue mentioned.
This would need to go via community Ideas or as a support request.

**Comment by pedrosousa** [comment]
Hi, @Highbury14 and @somehost !

> I saw this same grammatical error in the pop-up description text in OutSystems Service-Studio U.I, for this Entity-Property 'label attribute'.
> 
> Does it get fixed in the Service-Studio U.I also, when it is updated here in the documentation ?
> 
> Or is that in a different repository ?

The Service Studio UI labels and tooltips are in a different repository, but we try to keep them in sync. I just replicated your fix in that repository so that it's also corrected in the UI in an upcoming Service Studio release.

(I checked in Service Studio 11 Beta and the error is also there, in the tooltip for the "Label (plural)" property of Entities.)

Thank you both for your contribution, and keep sending your feedback! 📖

**Review by pedrosousa — APPROVED** [review]

**Pull request merged**
