### PR TITLE
Update secure-cookies-enable-secure-session.md

### PR DESCRIPTION
**Pull request by fcisco-mc**
Explains where the secure cookies configuration can be done in LifeTime. Original article points users to Factory Configuration app

### CODE REVIEW

**Comment by fcisco-mc** [comment]
I read, understood and accept the OutSystems CLA

**Comment by jonathanalgar** [comment]
@fcisco-mc thanks for taking the time to add this information. Apologies the review to get this published is very belated. Just to check, did you want to commit a screenshot to complement the text here?

https://github.com/OutSystems/docs-product/pull/342/files#diff-200f49e5c615f97623822ec9b3cf0ecfd7866590372ab529d12cd5511ef82c25R25

**Comment by jonathanalgar** [comment]
@outsystemsbot cla approve

**Review by jonathanalgar — APPROVED** [review]

**Comment by jonathanalgar** [comment]
@fcisco-mc thanks for another great contribution 🙂🚀

**Pull request merged**
