### PR TITLE
Add publish step apply CSP in ServiceCenter

### PR DESCRIPTION
**Pull request by joaorosado**
Adding the same steps that were already present above on the Lifetime version of the instructions.
Publish is necessary for the configurations to be effective in both scenarios but it was not explicit on the ServiceCenter steps leading to the conclusion that only using Apply Settings would be enough.

### CODE REVIEW

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Comment by joaorosado** [comment]
@outsystemsbot cla approve

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Pull request merged**
