### PR TITLE
Update mobile-app-update-scenarios.md

### PR DESCRIPTION
**Pull request by jlenriquez-os**
Hello team, the background of this request is related to this ticket #2371698 which was an improvement to be able to determine whether our customers developing mobile apps would need to do automatic or manual generation. These additional notes would help to clarify and our customers to be able to identify when and not manual generation is needed.

### CODE REVIEW

**Comment by rmlos** [comment]
Thanks, @jlenriquez-os! :) We'll have a look ate the update you suggested and let you know if we need more info about it.

**Comment by jlenriquez-os** [comment]
Thank you very much!

Regards,


Joel Enriquez | Technical Success Manager

m: +81 070 3896 9727 p: +81 03 4400 2695


Honored to be a Gartner Magic Quadrant Leader • Forrester Wave Leader •
CODiE Award Winner

**Comment by rmlos** [comment]
Related issue in the internal board is TK-3002.

**Comment by rmlos** [comment]
This pull request closes TK-3002 in Jira board. Thank you, @jlenriquez-os, for this pull request. We updated the document Mobile App Update Scenarios, but also added notes to the SSL Pinning document -- to make sure the important piece of information about external configuration is now more visible to our customers.

**Pull request merged**
