### PR TITLE
Added HTTPS requirement

### PR DESCRIPTION
**Pull request by sotnasm**
Application Server requires a valid SSL certificate to allow HTTPS communication because it interacts with ServerAPI and may result in errors if not guaranteed

### CODE REVIEW

**Comment by pjft** [comment]
@sotnasm - thank you so much for sending this over.

@pedrosousa and @rmlos - is there anything missing for this review?

**Comment by aabramos** [comment]
@rmlos Can I help with anything else regarding this pending review?

**Comment by rmlos** [comment]
We're in the process of getting more information about this pull request.

**Comment by rmlos** [comment]
After getting more information we now can help users identify and fix the issue. Thank you all for you contributions.

**Pull request merged**
