### PR TITLE
Update list-iterate.md

### PR DESCRIPTION
**Pull request by GHCMelo**
Break line added after step 1: "Add a For Each flow element to action flow." to keep example image below step.

**Before:**
image

**After:**
after

### CODE REVIEW

**Comment by GHCMelo** [comment]
> I read, understood and accept the OutSystems CLA

**Comment by GHCMelo** [comment]
> Hello @GHCMelo 👋
> 
> Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the 📝 [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
> 
> After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

I read, understood and accept the OutSystems CLA

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Review by OutSystemsAMM — APPROVED** [review]

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Comment by GHCMelo** [comment]
Hello, @OutSystemsAMM!

Thank you for merging.

Since it's merged, do you know how do I get the Outsystems Contributor Badge?

**Pull request merged**
