### PR TITLE
OnReady before Render?

### PR DESCRIPTION
**Pull request by TrustedSchool**
Confirm if I am wrong but, in the phrase "The On Ready event handler runs when the Screen or Block is ready, i.e. when the DOM is ready, after the first render." 
I think the last part is wrong "after the first render". Wouldn't it be: "before the first render"?

### CODE REVIEW

**Comment by TrustedSchool** [comment]
> I read, understood and accept the OutSystems CLA

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Review by OutSystemsAMM — APPROVED** [review]

**Comment by OutSystemsAMM** [comment]
@outsystemsbot cla approve

**Pull request merged**
